"""Shared species-name helpers for AI backends.

The mapping keys deliberately follow the scientific names emitted by the
models. Some keys reflect the model taxonomy rather than the most current
ornithological split; that keeps BirdNET and Perch outputs stable.
"""

from __future__ import annotations

SPECIES_TO_DUTCH: dict[str, str] = {
    "Accipiter gentilis": "Havik",
    "Accipiter nisus": "Sperwer",
    "Actitis hypoleucos": "Oeverloper",
    "Aegithalos caudatus": "Staartmees",
    "Alcedo atthis": "IJsvogel",
    "Alauda arvensis": "Veldleeuwerik",
    "Alectoris chukar": "Aziatische steenpatrijs",
    "Alopochen aegyptiaca": "Nijlgans",
    "Anas acuta": "Pijlstaart",
    "Anas clypeata": "Slobeend",
    "Anas crecca": "Wintertaling",
    "Anas penelope": "Smient",
    "Anas platyrhynchos": "Wilde Eend",
    "Anas querquedula": "Zomertaling",
    "Anas strepera": "Krakeend",
    "Anser albifrons": "Kolgans",
    "Anser anser": "Grauwe gans",
    "Anser brachyrhynchus": "Kleine rietgans",
    "Anthus pratensis": "Graspieper",
    "Anthus spinoletta": "Waterpieper",
    "Anthus trivialis": "Boompieper",
    "Apus apus": "Gierzwaluw",
    "Ardea alba": "Grote Zilverreiger",
    "Ardea cinerea": "Blauwe Reiger",
    "Aythya ferina": "Tafeleend",
    "Aythya fuligula": "Kuifeend",
    "Branta bernicla": "Rotgans",
    "Branta canadensis": "Grote Canadese gans",
    "Branta leucopsis": "Brandgans",
    "Bubo virginianus": "Amerikaanse oehoe",
    "Basileuterus rufifrons": "Roodkruinzanger",
    "Butorides striata": "Mangrovereiger",
    "Butorides virescens": "Groene reiger",
    "Buteo buteo": "Buizerd",
    "Carduelis carduelis": "Putter",
    "Certhia familiaris": "Boomkruiper",
    "Charadrius peronii": "Maleise Plevier",
    "Charadrius hiaticula": "Bontbekplevier",
    "Chloris chloris": "Groenling",
    "Chroicocephalus cirrocephalus": "Grijskopmeeuw",
    "Chroicocephalus novaehollandiae": "Australische Zilvermeeuw",
    "Chroicocephalus ridibundus": "Kokmeeuw",
    "Ciconia ciconia": "Ooievaar",
    "Coccothraustes coccothraustes": "Appelvink",
    "Coccothraustes vespertinus": "Avondappelvink",
    "Coloeus monedula": "Kauw",
    "Columba livia": "Rotsduif",
    "Columba palumbus": "Houtduif",
    "Corvus corax": "Raaf",
    "Corvus cornix": "Bonte Kraai",
    "Corvus corone": "Zwarte Kraai",
    "Corvus coronoides": "Australische Raaf",
    "Corvus frugilegus": "Roek",
    "Corvus monedula": "Kauw",
    "Corvus rhipidurus": "Waaierstaartraaf",
    "Corvus splendens": "Huiskraai",
    "Cuculus canorus": "Koekoek",
    "Curruca curruca": "Braamsluiper",
    "Cyanistes caeruleus": "Pimpelmees",
    "Cygnus cygnus": "Wilde zwaan",
    "Cygnus olor": "Knobbelzwaan",
    "Delichon urbicum": "Huiszwaluw",
    "Dendrocopos major": "Grote bonte specht",
    "Dendrocopos minor": "Kleine Bonte Specht",
    "Dryocopus martius": "Zwarte specht",
    "Egretta garzetta": "Kleine zilverreiger",
    "Egretta thula": "Sneeuwreiger",
    "Electron platyrhynchum": "Breedbekmotmot",
    "Emberiza citrinella": "Geelgors",
    "Emberiza hortulana": "Ortolaan",
    "Emberiza schoeniclus": "Rietgors",
    "Erithacus rubecula": "Roodborst",
    "Falco peregrinus": "Slechtvalk",
    "Falco subbuteo": "Boomvalk",
    "Falco tinnunculus": "Torenvalk",
    "Ficedula hypoleuca": "Bonte vliegenvanger",
    "Fratercula arctica": "Papegaaiduiker",
    "Fringilla coelebs": "Vink",
    "Fringilla montifringilla": "Keep",
    "Fulica atra": "Meerkoet",
    "Gallus gallus": "kip",
    "Gallinago gallinago": "Watersnip",
    "Gallinula chloropus": "Waterhoen",
    "Garrulus glandarius": "Gaai",
    "Garrulus lidthi": "Lidthgaai",
    "Haemorhous mexicanus": "Mexicaanse roodmus",
    "Haematopus ostralegus": "Scholekster",
    "Haliaeetus albicilla": "Zeearend",
    "Hirundo rustica": "Boerenzwaluw",
    "Hydrocoloeus minutus": "Dwergmeeuw",
    "Lanius collurio": "Grauwe Klauwier",
    "Lanius excubitor": "Klapekster",
    "Larus argentatus": "Zilvermeeuw",
    "Larus canus": "Stormmeeuw",
    "Larus delawarensis": "Ringsnavelmeeuw",
    "Larus fuscus": "Kleine Mantelmeeuw",
    "Larus marinus": "Grote Mantelmeeuw",
    "Larus michahellis": "Geelpootmeeuw",
    "Limosa limosa": "Grutto",
    "Linaria cannabina": "Kneu",
    "Locustella naevia": "Sprinkhaanzanger",
    "Lophophanes cristatus": "Kuifmees",
    "Loxia curvirostra": "Kruisbek",
    "Luscinia megarhynchos": "Nachtegaal",
    "Mareca strepera": "Krakeend",
    "Melanitta nigra": "Zwarte zee-eend",
    "Melospiza georgiana": "Moerasgors",
    "Milvus milvus": "Rode wouw",
    "Motacilla alba": "Witte Kwikstaart",
    "Motacilla cinerea": "Grote Gele Kwikstaart",
    "Motacilla flava": "Gele Kwikstaart",
    "Muscicapa striata": "Grauwe vliegenvanger",
    "Numenius arquata": "Wulp",
    "Nycticorax nycticorax": "Kwak",
    "Oriolus oriolus": "Wielewaal",
    "Parus major": "Koolmees",
    "Passer domesticus": "Huismus",
    "Passer montanus": "Ringmus",
    "Periparus ater": "Zwarte mees",
    "Pernis apivorus": "Wespendief",
    "Phalacrocorax carbo": "Aalscholver",
    "Phoenicopterus ruber": "Amerikaanse Flamingo",
    "Phoenicurus ochruros": "Zwarte roodstaart",
    "Phoenicurus phoenicurus": "Gekraagde roodstaart",
    "Phylloscopus collybita": "Tjiftjaf",
    "Phylloscopus trochilus": "Fitis",
    "Pica pica": "Ekster",
    "Picus viridis": "Groene Specht",
    "Pluvialis apricaria": "Goudplevier",
    "Podiceps cristatus": "Fuut",
    "Poecile montanus": "Matkop",
    "Poecile palustris": "Glanskop",
    "Pygoscelis adeliae": "Adeliepinguin",
    "Pyrrhula pyrrhula": "Goudvink",
    "Rallus aquaticus": "Waterral",
    "Regulus ignicapilla": "Vuurgoudhaan",
    "Regulus regulus": "Goudhaan",
    "Riparia riparia": "Oeverzwaluw",
    "Saxicola rubetra": "Paapje",
    "Saxicola torquatus": "Roodborsttapuit",
    "Scolopax rusticola": "Houtsnip",
    "Sitta europaea": "Boomklever",
    "Spinus spinus": "Sijs",
    "Spheniscus magellanicus": "Magelhaenpinguin",
    "Stercorarius skua": "Grote jager",
    "Sterna hirundo": "Visdief",
    "Streptopelia decaocto": "Turkse tortel",
    "Streptopelia turtur": "Zomertortel",
    "Sturnus vulgaris": "Spreeuw",
    "Sylvia atricapilla": "Zwartkop",
    "Sylvia borin": "Tuinfluiter",
    "Sylvia communis": "Grasmus",
    "Tadorna tadorna": "Bergeend",
    "Tadorna tadornoides": "Australische bergeend",
    "Tringa nebularia": "Groenpootruiter",
    "Tringa totanus": "Tureluur",
    "Troglodytes troglodytes": "Winterkoning",
    "Turdus iliacus": "Koperwiek",
    "Turdus merula": "Merel",
    "Turdus philomelos": "Zanglijster",
    "Turdus pilaris": "Kramsvogel",
    "Turdus viscivorus": "Grote Lijster",
    "Vanellus vanellus": "Kievit",
}


def get_dutch_name(scientific_name: str) -> str:
    """Return the Dutch common name for a scientific name when known."""
    return SPECIES_TO_DUTCH.get((scientific_name or "").strip(), "")
