tag_categories = {
    "🌿 Nature": [
        "stream",
        "mountain",
        "forest",
        "dune",
        "cave",
        "heath",
        "lake",
        "marsh",
        "nature reserve",
        "river",
        "beach",
        "valley",
        "field",
        "pond",
        "waterfall",
        "meadow",
        "sea",
    ],
    "🏙️ Urban / Human": [
        "construction site",
        "park",
        "square",
        "school",
        "playground",
        "station",
        "street",
        "traffic",
        "store",
    ],
    "🐦 Animals (wild & domestic)": [
        "hedgehog",
        "duck",
        "goat",
        "dog",
        "cat",
        "cow",
        "frog",
        "rabbit",
        "mouse",
        "horse",
        "sheep",
        "woodpecker",
        "owl",
        "pig",
        "bat",
        "bird",
        "fox",
        "swan",
    ],
    "🦗 Insects & Small animals": [
        "bee",
        "bumblebee",
        "cricket",
        "mosquito",
        "caterpillar",
        "snail",
        "grasshopper",
        "butterfly",
        "fly",
        "worm",
        "wasp",
    ],
    "🌧️ Weather & Elements": [
        "dew",
        "ice",
        "fog",
        "thunderstorm",
        "rain",
        "snow",
        "storm",
        "wind",
        "sun",
    ],
    "⏰ Time of day": ["evening", "afternoon", "night", "morning", "sunset", "sunrise"],
    "🛠️ Sound type / Activity": [
        "construction noise",
        "nearby",
        "crowd",
        "machines",
        "voices",
        "silence",
        "distant",
        "traffic",
        "footsteps",
    ],
    "🎧 Recording quality": [
        "ambient",
        "close",
        "clear",
        "mono",
        "noise",
        "stereo",
        "distant",
        "distortion",
    ],
}
